name: check

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '1 2 5 * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        engine: [pdflatex, lualatex]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          show-progress: ''
      - name: Install TeX Live
        uses: zauguin/install-texlive@v3
        with:
           package_file: Texlivefile
      - name: Generate files based on cidarticle.{ins.dtx}
        run: |
          pdflatex cidarticle.ins
          pdflatex cidarticle.dtx
          pdflatex cidarticle.dtx
          pdflatex cidarticle.dtx
      - name: Check for modifications
        run: |
          git update-index --refresh
          if ! git diff-index --quiet HEAD --; then
            echo "Worktree is not clean."
            git diff-index --name-status HEAD
            exit 1
          fi

      - name: Install NimbusSanL-Reg
        uses: awalsh128/cache-apt-pkgs-action@latest
        if: matrix.engine == 'lualatex'
        with:
          packages: gsfonts
          version: 1.0

      - run: ${{ matrix.engine }} cidarticle-author-template
      - run: texlogsieve cidarticle-example.log

      - name: Upload build result
        uses: actions/upload-artifact@v3
        with:
          name: PDFs-${{ matrix.engine }}
          path: |
            cidarticle-author-template.pdf
            *.log

      - name: Prepare GH pages content
        if: github.ref == 'refs/heads/main' && matrix.engine == 'lualatex'
        run: |
          set -e
          mkdir /tmp/gh-pages
          cp README.md /tmp/gh-pages/index.md
          cp *.pdf /tmp/gh-pages

      - name: Deploy to GH pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main' && matrix.engine == 'lualatex'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /tmp/gh-pages

      - name: Install dependencies for ctanify
        if: matrix.engine != 'lualatex'
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libfile-copy-recursive-perl
          version: 1.0

      - name: Prepare for CTAN
        if: matrix.engine != 'lualatex'
        run: ./prepare_for_CTAN

      - name: Upload CTAN build
        if: matrix.engine != 'lualatex'
        uses: actions/upload-artifact@v3
        with:
          name: CTAN-${{ matrix.engine }}
          path: '*.tar.gz'
  changelog:
    name: CHANGELOG.md
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          show-progress: ''
      - uses: jbangdev/jbang-action@v0.114.0
        with:
          script: com.github.nbbrd.heylogs:heylogs-cli:0.7.2:bin
          scriptargs: "check CHANGELOG.md"
